/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AirStudios (https://sketchfab.com/sebbe613)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-5f9c35be31a047928eace8b415a8ee3a
Title: Earth
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

export default function Earth(props) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + "models/earth (2).glb");

  const earthGroup = useRef();
  const meshesRef = useRef([]);

  useEffect(() => {
    if (earthGroup.current) {
      // Make all materials transparent initially
      meshesRef.current.forEach((m) => {
        if (m.material) {
          // m.material.transparent = true;
          // m.material.opacity = 0;
        }
      });

      // Starting position offscreen on z +10
      gsap.set(earthGroup.current.position, { x: 15 });

      // Animate into place
      gsap.to(earthGroup.current.position, {
        x: 0,
        duration: 1.5,
        ease: "easeInOut",
      });
    }
  }, []);

  return (
    <group {...props} dispose={null} ref={earthGroup}>
      <group scale={96.724}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere1_phong1_0.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere1_phong1_0_1.geometry}
          material={materials.phong1}
        />
      </group>
      <group scale={97.464}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere4_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere4_lambert6_0_1.geometry}
          material={materials.lambert6}
        />
      </group>
      <group scale={98.098}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5_lambert7_0_1.geometry}
          material={materials.lambert7}
        />
      </group>
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "models/earth (2).glb");