/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'




export default function Particals(props) {

  const particlesRef = useRef()

  
  useGSAP(() => {
    if (particlesRef.current) {
      // Ensure material supports transparency
      particlesRef.current.material.transparent = true;
      // Begin invisible
      particlesRef.current.material.opacity = 0;

      // Fade in over 2 seconds
      gsap.to(particlesRef.current.material, {
        opacity: 1,
        duration: 2,
        ease: "power2.inOut",
        delay: 0.7, // small delay for cinematic staging
      });

      // Continuous gentle rotation
      // gsap.to(particlesRef.current.rotation, {
      //   z: "+=" + Math.PI * 2, // full circle
      //   duration: 60,          // very slow
      //   ease: "none",
      //   repeat: -1,
      // });
    }
  }, []);


  const { nodes, materials } = useGLTF('models/need_some_space.glb')
  return (
    <group  {...props} dispose={null}>
      <points
        ref={particlesRef}
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </group>
  )
}

useGLTF.preload('models/need_some_space.glb')
